packageExtensions:
  '@eslint/eslintrc@0.1.0':
    dependencies:
      globals: ^13.2.0
      ignore: ^4.0.6
      lodash: ^4.17.20
      minimatch: ^3.0.4
  '@typescript-eslint/experimental-utils@2.32.0':
    dependencies:
      json-schema: ^0.2.5
  eslint-plugin-sort-keys-fix@1.1.1:
    dependencies:
      espree: ^6.1.2
      esutils: ^2.0.2
      natural-compare: ^1.4.0
  eslint-plugin-typescript-sort-keys@1.3.0:
    dependencies:
      globals: ^13.2.0
    peerDependencies:
      '@typescript-eslint/parser': ^4.0.1
      typescript: ^4.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.2.2.cjs
