name: Lint

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Lint
        run: yarn lint-workspace
